name: flutter_robust_starter
description: "A robust, production-ready Flutter starter architecture with Dio, Clean Architecture, and essential core services."
version: 1.1.0
homepage: https://github.com/tryadnancode/template_project_handles_apis
repository: https://github.com/tryadnancode/template_project_handles_apis
issue_tracker: https://github.com/tryadnancode/template_project_handles_apis/issues

environment:
  sdk: ^3.10.8

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.9.1
  get_it: ^9.2.1
  shared_preferences: ^2.5.4
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
